const DESTINATIONS = [
    "TRADER JOE'S", "FARMERS MKT", "TALL GRASS", "MIGHTY-O", "REUBEN'S",
    "CAFFE UMBRIA", "PCC MARKET", "THE LOCKS", "FRED MEYER", "NORDIC MUSEUM",
    "GOLDEN GARDENS", "UN BIEN", "THE WALRUS", "HOT CAKES", "STOUP BREWING",
    "OBEC BREWING", "URBAN FAMILY", "FAIR ISLE", "GREAT NOTION", "MAIN ST GYROS",
    "BALLARD COFFEE", "SONIC BOOM", "CUPCAKE ROYALE", "SALT & STRAW", "BITTERROOT",
    "THE MATADOR", "KINGS HARDWARE", "HATTIES HAT", "OCHO", "TRACTOR TAVERN"
];

const TILE_SIZE = 120;
const MAP_W = 42;
const MAP_H = 42;
